### ISSUE TITLE
Only represent personal suggestions for this module.

### ISSUE THREAD

**Issue by zxnhrdz** [azerothcore/mod-costumes#19]
![DBDCO4W7VD%DR)Z0~0OXO](https://user-images.githubusercontent.com/110412571/217971464-d09fc2e6-ff9f-427a-8501-efeefef876bb.png)
![DT$_ TRKNUE6}0{EDD20Q~F](https://user-images.githubusercontent.com/110412571/217971491-88d7e9ae-64b0-43c9-9175-e1bf48233199.png)
This module has been used for a long time and feels very good. At present, the only regret is that you can't use mounts after most of the shape changes. Only an individual appearance can. Upload two examples: Thassarian and the dark Prince Arthas.
Among them: Thassarian can use the mount after transformation, but the dark Prince Arthas can't.

**Comment by Nyeriah** [comment]
There's a core limitation that prevents you from using mounts while transmorphed. There's little to nothing that can be done about this as an exception would also allow things like druids to mount while shapeshifted.

**Comment by zxnhrdz** [comment]
Thank you for your answer.

**Comment by Nyeriah** [comment]
Furthermore, not all models have a mount animation, which would also hinder the ability to provide what is desired here, even if the core limitation was to be bypassed somehow. Thanks for your suggestion but I'll be closing this as such, I am sorry.
